### ISSUE TITLE
StackExchange Radis Configuration

### ISSUE THREAD

**Issue by maksudcs** [socioboard/Socioboard-Core-3.0#11]
Hey, 
I am getting error on Radis connection.

**"It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING"**

Any one help me to set Redis Configuration..

**Comment by socioboard** [comment]
Hi maksudcs,
The error you are getting is usually a sign that you have not set abortConnect=false in your connection string. The default value for abortConnect is true, which makes it so that StackExchange.Redis won't reconnect to the server automatically under some conditions. We strongly recommend that you set abortConnect=false in your connection string so that SE.Redis will auto-reconnect in the background if a network blip occurs.

**Comment by socioboard** [comment]
Hi maksudcs,
I hope you have find your solution.so closing this issue.In future if you have any query 
please let us know.
Thanks
Socioboard Team
