### ISSUE TITLE
Does not get "My Feeds"

### ISSUE THREAD

**Issue by maksudcs** [socioboard/Socioboard-Core-3.0#12]
Has any configuration to gett My Feeds (Facebook, twitter, Instagram,Google).  i am tired, already 2 days lost to get "My Feeds".

Please help me. what to do ??

**Comment by maksudcs** [comment]
Mr Sumit Ghosh,  please suggest what i am missing??

**Comment by socioboard** [comment]
Hi Maksudcs,
Have you done any mongo setup in local?

**Comment by maksudcs** [comment]
yes i have install mongoDB community version and run mongod.exe for MongoDB server in according to this tutorial. https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/#overview 

When we feed from facebook/twitter, **_Model/MongoRepository.cs_** always return 0 record.
**another question is that when Social  Network (facebook, twitter) data store in MongoDB ?**

**Comment by socioboard** [comment]
Q 1)When we feed from facebook/twitter, Model/MongoRepository.cs always return 0 record.
 ans : yes because no records found in your mongo db table.

Q 2)another question is that when Social Network (facebook, twitter) data store in MongoDB ?
ans: a)when we add socialprofile  b) run data services to add the data in mongo db.

**Comment by maksudcs** [comment]
@socioboard thanks for reply..
 please clarify for **b) run data services to add the data in mongo db.**
  How to run data service ??

**Comment by socioboard** [comment]
@maksudcs 
here our support team skype id i.e  socioboard.support

Thanks
Socioboard Team
